### ISSUE TITLE
지도, 버튼 관련 TODO

### ISSUE THREAD

**Issue by Nougaga** [heej93/Mini_project#3]
- [x] 1. 카테고리 기본값 복구

- [x] 2. 텍스트, 버튼 id 복구

- [x] 3. ready에 버튼 비활성화 관련 코드 복구

```
      $('#search_sp_btn').prop('disabled', true);
      $('#search_sp_text').keyup(function () {
        $('#search_sp_btn').prop('disabled', this.value === "");
      })

```

- [x] 4. iframe용 modal을 최적경로버튼에서 길찾기 버튼으로 옮기기

- [x] 5. views.py 충돌나면 2.5>2.0 버전으로 push

**Comment by Nougaga** [comment]
DONE
4
